server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  application:
    name: lingopress
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
    show-sql: false
  server:
    tomcat:
      uri-encoding: UTF-8

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${datasource-username}
    password: ${datasource-password}
    url: jdbc:postgresql://lingopress-db:5432/lingopress
    hikari:
      max-lifetime: 25800 # Possibly consider using a shorter maxLifetime value. 오류로 인해 추가

  rabbitmq:
    host: ${ai-url}
    port: 5672
    username: ${rabbitmq-username}
    password: ${rabbitmq-password}

  mail:
    host: smtp.gmail.com
    port: 587
    username: dev.lingopress@gmail.com
    password: ${gmail-password}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: true
            required: true
        debug: false


jwt:
  secret: ${jwt-secret}

deepl:
  auth-key: ${deepl-key}

chatgpt:
  auth-key: ${chatgpt-key}


lingo-ai:
  url: ${ai-url}


greeting:
  message: this is prod application.yml


springdoc:
  api-docs:
    enabled: true


management:
  endpoints:
    web:
      exposure:
        include: "prometheus, health, info, env, beans, configprops, loggers, heapdump, threaddump, metrics, httptrace, mappings, scheduledtasks, jolokia, jolokia"

sentry:
  dsn: ${sentry-dsn}
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0
  environment: production


oauth2:
  google:
    client:
      id: 721227479427-hkglvdqhrfa53nqqlfar5ecn32hvg3ii.apps.googleusercontent.com
      secret: ${google-secret}
    # redirect-uri: http://localhost:8080/api/v1/users/oauth2/google
    redirect-uri: https://lingopress.me/login/oauth2/google

